
# Generated by stc version 0.8.3
# date                    : 2020/02/04 10:47:24
# Turbine version         : 1.2.3
# Input filename          : /pfs/data3/project/fh1-project-devel/th7356/work/GITLAB/grk2450-p6-workflows/wf-systems/swift-t/matrix/tmm_tutorial/test-b-simple.swift
# Output filename         : /pfs/data3/project/fh1-project-devel/th7356/work/GITLAB/grk2450-p6-workflows/wf-systems/swift-t/matrix/tmm_tutorial/test-b-simple.tcl
# STC home                : /pfs/data3/project/fh1-project-devel/th7356/software/swift-t-install/stc
# Turbine home            : /home/fh1-project-devel/th7356/software/swift-t-install/turbine
# Compiler settings:
# stc.auto-declare              : true
# stc.c_preprocess              : true
# stc.checkpointing             : true
# stc.compiler-debug            : true
# stc.debugging                 : COMMENTS
# stc.ic.output-file            : 
# stc.input_filename            : test-b-simple.swift
# stc.log.file                  : 
# stc.log.trace                 : false
# stc.must_pass_wait_vars       : true
# stc.opt.algebra               : true
# stc.opt.array-build           : true
# stc.opt.batch-refcounts       : true
# stc.opt.cancel-refcounts      : true
# stc.opt.constant-fold         : true
# stc.opt.controlflow-fusion    : true
# stc.opt.dataflow-op-inline    : true
# stc.opt.dead-code-elim        : true
# stc.opt.demote-globals        : true
# stc.opt.disable-asserts       : false
# stc.opt.expand-loop-threshold-insts: 256
# stc.opt.expand-loop-threshold-iters: 16
# stc.opt.expand-loops          : false
# stc.opt.finalized-var         : true
# stc.opt.flatten-nested        : true
# stc.opt.full-function-inline  : false
# stc.opt.full-unroll           : false
# stc.opt.function-always-inline-threshold: 5
# stc.opt.function-inline       : true
# stc.opt.function-inline-threshold: 50
# stc.opt.function-signature    : true
# stc.opt.hoist                 : true
# stc.opt.hoist-refcounts       : true
# stc.opt.loop-simplify         : true
# stc.opt.max-iterations        : 10
# stc.opt.merge-refcounts       : true
# stc.opt.piggyback-refcounts   : true
# stc.opt.pipeline              : false
# stc.opt.propagate-aliases     : true
# stc.opt.reorder-insts         : false
# stc.opt.shared-constants      : true
# stc.opt.unroll-loop-threshold-insts: 192
# stc.opt.unroll-loop-threshold-iters: 8
# stc.opt.unroll-loops          : true
# stc.opt.value-number          : true
# stc.opt.wait-coalesce         : true
# stc.output_filename           : test-b-simple.tcl
# stc.preproc.force-cpp         : false
# stc.preproc.force-gcc         : false
# stc.preprocess_only           : false
# stc.profile                   : false
# stc.refcounting               : true
# stc.rpath                     : 
# stc.stc_home                  : /pfs/data3/project/fh1-project-devel/th7356/software/swift-t-install/stc
# stc.turbine.version           : 1.2.3
# stc.turbine_home              : /home/fh1-project-devel/th7356/software/swift-t-install/turbine
# stc.version                   : 0.8.3

# Metadata:

package require turbine 1.2.3
namespace import turbine::*


proc swift:constants {  } {
    turbine::c::log "function:swift:constants"
}


proc swift:main {  } {
    turbine::c::log "function: __entry"
    # Var: blob u:b test-b-simple.swift:5:0
    # Var: file u:data test-b-simple.swift:4:0
    # Var: float[int] u:v test-b-simple.swift:6:0
    # Var: $file v:data VALUE_OF [file:data]
    lassign [ adlb::multicreate [ list blob 1 1 1 ] [ list container integer float 2 2 3 ] ] u:b u:v
    turbine::c::log "allocated u:b=<${u:b}> u:v=<${u:v}>"
    lassign [ turbine::make_file_tds [ adlb::multicreate [ list file 1 1 2 ] ] [ list 0 ] ] u:data
    set tcltmp:init_rc 1
    set v:data [ turbine::create_local_file_ref "" ${tcltmp:init_rc} 0 ]
    turbine::input_file_local v:data "input.txt"
    turbine::store_file ${u:data} v:data 1
    turbine::blob_read [ list ${u:b} ] [ list ${u:data} ]
    set a:t:11 [ adlb::subscript_container ${u:v} 0 ]
    turbine::rule [ list ${u:b} ] "floats_from_blob-argwait ${u:b} ${u:v}"
    turbine::rule [ list ${a:t:11} ] "__entry-call_foreign-printf-2 {${a:t:11}}"
    turbine::decr_local_file_refcount v:data
}


proc floats_from_blob-argwait { u:b u:v } {
    # Var: $blob v:b RENAMED [$blob:__v:b]
    # Var: $float$[int] v:f RENAMED [$float$[int]:__v:f]
    # Var: $int v:t:8 VALUE_OF [int:__t:8]
    # Var: $int v:t:15 VALUE_OF [int:__t:15]
    # Var: $float v:alias:t:14 VALUE_OF [float:__alias:t:14]
    set v:b [ turbine::retrieve_blob ${u:b} 1 ]
    set v:f [ turbine::blob2floats_impl ${v:b} ]
    turbine::build_rec ${u:v} ${v:f} [ list container integer float ] 0 1
    set v:t:8 [ dict size ${v:f} ]
    set v:t:15 [ expr { ${v:t:8} - 1 } ]
    set a:t:14 [ adlb::subscript_container ${u:v} ${v:t:15} ]
    set v:alias:t:14 [ turbine::retrieve_float ${a:t:14} CACHED 1 ]
    set tcltmp:prio [ turbine::get_priority ]
    turbine::set_priority ${tcltmp:prio}
    adlb::spawn 0 "__entry-call_foreign-printf ${v:t:8}"
    turbine::reset_priority
    set tcltmp:prio [ turbine::get_priority ]
    turbine::set_priority ${tcltmp:prio}
    adlb::spawn 0 "__entry-call_foreign-printf-1 ${v:alias:t:14}"
    turbine::reset_priority
    turbine::free_local_blob ${v:b}
    adlb::write_refcount_decr ${u:v} 1
}


proc __entry-call_foreign-printf { v:t:8 } {
    # Var: $void v:t:6 VALUE_OF [void:__t:6]
    set v:t:6 [ turbine::printf_local "size(v) = %i" ${v:t:8} ]
}


proc __entry-call_foreign-printf-1 { v:alias:t:14 } {
    # Var: $void v:t:12 VALUE_OF [void:__t:12]
    set v:t:12 [ turbine::printf_local "v\[last\]=%0.2f" ${v:alias:t:14} ]
}


proc __entry-call_foreign-printf-2 { a:t:11 } {
    # Var: $float v:alias:t:11 VALUE_OF [float:__alias:t:11]
    # Var: $void v:t:9 VALUE_OF [void:__t:9]
    set v:alias:t:11 [ turbine::retrieve_float ${a:t:11} CACHED 1 ]
    set v:t:9 [ turbine::printf_local "v\[0\]=%0.2f" ${v:alias:t:11} ]
}

turbine::defaults
turbine::declare_custom_work_types COASTER
turbine::init $servers "Swift"
turbine::enable_read_refcount
adlb::declare_struct_type 16 s:location [ list "rank" integer "strictness" string "accuracy" string ]
turbine::check_constants "WORKER\[WORKER\]" ${turbine::WORK_TASK} 0 "CONTROL" ${turbine::WORK_TASK} 0 "ADLB_RANK_ANY" ${adlb::RANK_ANY} -100
adlb::add_debug_symbol 1 "b" "test-b-simple:5:0"
adlb::add_debug_symbol 2 "data" "test-b-simple:4:0"
adlb::add_debug_symbol 3 "v" "test-b-simple:6:0"
turbine::start swift:main swift:constants
turbine::finalize
